// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctxuzbdudqsexdlcspyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0eHV6YmR1ZHFzZXhkbGNzcHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzYwOTAsImV4cCI6MjA2NzY1MjA5MH0.uQGUc4MgUrs54xNwqsZV6TmBYEkrSCnQCxoyfniL-24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});